# Generated by Django 4.1.7 on 2023-03-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformcredentials',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='platform',
            name='isOrderSyncProcessing',
            field=models.BooleanField(default=False),
        ),
    ]
